apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices-app
type: Opaque
data:
  # Base64 encoded values (use: echo -n "value" | base64)
  postgres-password: cG9zdGdyZXMxMjM=  # postgres123
  redis-password: cmVkaXMxMjM=          # redis123
  rabbitmq-password: YWRtaW4xMjM=       # admin123
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1oZXJlLW1ha2UtaXQtbG9uZy1hbmQtcmFuZG9t  # your-super-secret-jwt-key-here-make-it-long-and-random
